### PR TITLE
Add Flex utilities

### PR DESCRIPTION
**Pull request by arippberger**
Adds bootstraps flex utilities, which greatly improve the capabilities of the Bootstrap grid: direction, content justification, 
alignment, etc

### CODE REVIEW

**Comment by robabbott** [comment]
@arippberger Does this need to be in the starter theme?  Seems like it might be more of a per project decision?

**Comment by arippberger** [comment]
@robabbott I'd argue this is going to be used in 90% of projects, so it should just be included by default.

**Comment by JMRhodes** [comment]
@arippberger I'm fine including this. Just make sure we remember that Bootstrap is being included mainly for the grid, we want to utilize our BEM classes as much as possible within our projects.

**Comment by sreigle** [comment]
You can also just import this file which is made to be the stripped down version of bootstrap: https://github.com/twbs/bootstrap/blob/master/scss/bootstrap-grid.scss

**Comment by robabbott** [comment]
@arippberger How would you feel about making a second "section" in main.scss then?  Since it's not really part of the base framework - more of a utility extension.  Maybe something like this?

    // Bootstrap Utilities
   @import '../../node_modules/bootstrap/scss/utilities/flex';

**Comment by arippberger** [comment]
@JMRhodes I like Sam's suggestion of just including the Bootstrap's prebuilt grid file. Thoughts?

**Comment by arippberger** [comment]
@robabbott the flex utilities include the classes for centering columns. I was being conservative with 90% - probably like 99% of project will/should use that.

**Comment by robabbott** [comment]
@arippberger Right, I am aware of what it does and other display utility helper classes as well.  But, like Justin said it doesn't follow our BEM standards and I think it's up to the developer if they want to utilize it.

**Comment by JMRhodes** [comment]
> @JMRhodes I like Sam's suggestion of just including the Bootstrap's prebuilt grid file. Thoughts?

That's fine, let's update to import just the grid ile

**Comment by JMRhodes** [comment]
@arippberger are we going to run into conflicts with the variables file?

**Pull request closed without merging**
